### ISSUE TITLE
Daisy UI for the Backend : Combine Dashboard and Feed

### ISSUE THREAD

**Issue by abhisek-1221** [RescueRadar/resque-radar#4]
### Illustration

- Pull the latest commits
- visit `http://127.0.0.1:8000/feed/`
- Agency Posts on Feed: CRUD operations on validated agencies which I recently updated in backend are working properly. 
- **NOTE**:Agency have access to **edit** and **delete** their own post only. Incase they try to **click** on **delete** or **edit** on other agencies posts then it `redirects them back to the feed`.

> System Design Recap: The Dashboard (home page after login/registration) was supposed to be the main feed where latest posts from agency should have been displayed. Apparently as of now it only contains agency information which could have been a lot more informative by this minor change as per the layout proposed in the prototype

### TASK

- Add Daisy UI to the recently added templates
- If possible , align the current agency information in the dashboard to a SIDEBAR and add the agency posts to the main inner layout

After that I'll add the backend for search and filter bar as well as notifications, currently working on chatrooms.

**Comment by ChiragAgg5k** [comment]
Got it 👍🏻
